### ISSUE TITLE
v2.0.0 not compatible with Serverless v2

### ISSUE THREAD

**Issue by mdwt** [gozup/serverless-ssm-fetch#17]
Hi there,

The recent logging change is not backward compatible to v2.* of serverless.  Is there a way to make the logger optional?

```
 Type Error ----------------------------------------------
 
  TypeError: Cannot read property 'log' of undefined
      at new SsmFetch (/usr/local/lib/node_modules/serverless-ssm-fetch/dist/serverless-ssm-fetch.js:23:20)
      at PluginManager.addPlugin (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:114:28)
      at /usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:163:33
      at Array.forEach (<anonymous>)
      at PluginManager.loadAllPlugins (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:163:8)
      at Serverless.init (/usr/local/lib/node_modules/serverless/lib/Serverless.js:213:30)
      at async /usr/local/lib/node_modules/serverless/scripts/serverless.js:585:7
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              12.22.2
     Framework Version:         2.69.1
     Plugin Version:            5.5.1
     SDK Version:               4.3.0
     Components Version:        3.18.1
```

**Comment by gozup** [comment]
Hey @mdwt,

As mentioned in the README, v1 is compatible with version 2 of serverless, since v2 is for the upcoming serverless v3.

This breaking change is also mentioned in the plug-in 2.0.0 release.

Have a good day!

**Comment by gozup** [comment]
@mdwt you can use the 1.1.2 instead that has also been release 3 days ago.

**Comment by mdwt** [comment]
Ah I missed that in the README, thanks for the update!
